// src/core/config.ts
import Decimal from "break_eternity.js";

export const VERSION = "1.1.0-alpha";

export const GAME_CONFIG = {
  serialization: {
    saveVersion: "3.0.0",
  },

  tickRate: 100,
  offlineCapMs: 86_400_000,

  resources: {
    starting: {
      money: new Decimal(10),
      crypto: new Decimal(0),
      compute: new Decimal(10),
      reputation: new Decimal(0),
    },
    display: {
      money: { label: "$Money", shortLabel: "$" },
      crypto: { label: "Crypto Coins", shortLabel: "CR" },
      compute: { label: "Compute Resources", shortLabel: "CPU" },
      reputation: { label: "Reputation", shortLabel: "REP" },
    },
  },

  reputation: {
    whitehatThreshold: new Decimal(100),
    blackhatThreshold: new Decimal(-100),
  },

  activities: {
    basicCryptoMining: {
      baseCost: { compute: new Decimal(1) },
      baseYieldPerSecond: { crypto: new Decimal(0.5) },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.15),
      yieldScalingRate: new Decimal(0.1),
      maxLevel: 100,
    },
    bugBountyHunting: {
      baseCost: { money: new Decimal(5) },
      baseYieldPerSecond: { money: new Decimal(2), reputation: new Decimal(0.1) },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.2),
      yieldScalingRate: new Decimal(0.15),
      maxLevel: 100,
      reputationGate: { min: new Decimal(-100) },
    },
    passwordCracking: {
      baseCost: { compute: new Decimal(2) },
      baseYieldPerSecond: { money: new Decimal(1), crypto: new Decimal(0.3), reputation: new Decimal(-0.2) },
      consumesPerSecond: { compute: new Decimal(0.01) },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.18),
      yieldScalingRate: new Decimal(0.12),
      maxLevel: 100,
      reputationGate: { max: new Decimal(100) },
    },
    computeLeasing: {
      baseCost: { compute: new Decimal(3) },
      baseYieldPerSecond: { money: new Decimal(1.5) },
      actionUnlockRequirements: { scanNetwork: 5 },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.15),
      yieldScalingRate: new Decimal(0.1),
      maxLevel: 100,
    },
    dataIndexing: {
      baseCost: { money: new Decimal(8) },
      baseYieldPerSecond: { money: new Decimal(0.5), compute: new Decimal(0.1) },
      actionUnlockRequirements: { mineLocally: 3 },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.12),
      yieldScalingRate: new Decimal(0.1),
      maxLevel: 100,
    },
    defensiveAudit: {
      baseCost: { money: new Decimal(15) },
      baseYieldPerSecond: { money: new Decimal(3), reputation: new Decimal(0.2) },
      actionUnlockRequirements: { bugBounty: 5 },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.22),
      yieldScalingRate: new Decimal(0.12),
      maxLevel: 100,
      reputationGate: { min: new Decimal(0) },
    },
    threatIntelAnalysis: {
      baseCost: { money: new Decimal(30), compute: new Decimal(5) },
      baseYieldPerSecond: { money: new Decimal(5), reputation: new Decimal(0.5) },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.25),
      yieldScalingRate: new Decimal(0.15),
      maxLevel: 100,
      reputationGate: { min: new Decimal(50) },
      requiresResearchUnlock: true,
    },
    botnetExpansion: {
      baseCost: { crypto: new Decimal(5) },
      baseYieldPerSecond: { compute: new Decimal(0.5), crypto: new Decimal(0.2) },
      actionUnlockRequirements: { passwordAttempt: 10 },
      consumesPerSecond: { money: new Decimal(0.1) },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.2),
      yieldScalingRate: new Decimal(0.1),
      maxLevel: 100,
      reputationGate: { max: new Decimal(0) },
    },
    zeroDayResearch: {
      baseCost: { money: new Decimal(20), crypto: new Decimal(10) },
      baseYieldPerSecond: { crypto: new Decimal(2), reputation: new Decimal(-1) },
      levelCostScaling: "exponential" as const,
      yieldScaling: "linear" as const,
      costScalingRate: new Decimal(1.3),
      yieldScalingRate: new Decimal(0.15),
      maxLevel: 100,
      reputationGate: { max: new Decimal(-50) },
      requiresResearchUnlock: true,
    },
  },

  research: {
    parallelProcessing: {
      path: "shared" as const,
      cost: { compute: new Decimal(20) },
      prerequisites: [] as string[],
      position: { x: 0, y: 0 },
      effects: [{ type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.2) }],
    },
    distributedSchedulers: {
      path: "shared" as const,
      cost: { compute: new Decimal(40), money: new Decimal(30) },
      prerequisites: ["parallelProcessing"] as string[],
      position: { x: 1, y: 0 },
      effects: [
        { type: "activityYieldMultiplier" as const, target: "basicCryptoMining", value: new Decimal(1.2) },
        { type: "activityYieldMultiplier" as const, target: "computeLeasing", value: new Decimal(1.2) },
      ],
    },
    protocolOptimization: {
      path: "shared" as const,
      cost: { compute: new Decimal(80), crypto: new Decimal(20) },
      prerequisites: ["distributedSchedulers"] as string[],
      position: { x: 2, y: 0 },
      effects: [
        { type: "resourceMultiplier" as const, target: "money", value: new Decimal(1.15) },
        { type: "resourceMultiplier" as const, target: "crypto", value: new Decimal(1.1) },
      ],
    },
    responsibleDisclosure: {
      path: "whitehat" as const,
      cost: { money: new Decimal(60) },
      prerequisites: [] as string[],
      reputationGate: { min: new Decimal(0) },
      position: { x: 0, y: 1 },
      effects: [
        { type: "activityYieldMultiplier" as const, target: "bugBountyHunting", value: new Decimal(1.35) },
        { type: "reputationGainMultiplier" as const, value: new Decimal(1.5) },
      ],
    },
    defensiveAutomation: {
      path: "whitehat" as const,
      cost: { money: new Decimal(120), compute: new Decimal(30) },
      prerequisites: ["responsibleDisclosure"] as string[],
      reputationGate: { min: new Decimal(25) },
      position: { x: 1, y: 1 },
      effects: [
        { type: "activityYieldMultiplier" as const, target: "defensiveAudit", value: new Decimal(1.45) },
        { type: "activityYieldMultiplier" as const, target: "threatIntelAnalysis", value: new Decimal(1.35) },
      ],
    },
    trustedResearchNetwork: {
      path: "whitehat" as const,
      cost: { money: new Decimal(250), compute: new Decimal(80) },
      prerequisites: ["defensiveAutomation"] as string[],
      reputationGate: { alignment: "whitehat" as const },
      position: { x: 2, y: 1 },
      effects: [
        { type: "activityUnlock" as const, target: "threatIntelAnalysis", value: new Decimal(1) },
        { type: "upgradeUnlock" as const, target: "signatureCorrelation", value: new Decimal(1) },
      ],
    },
    exploitAutomation: {
      path: "blackhat" as const,
      cost: { crypto: new Decimal(12) },
      prerequisites: [] as string[],
      reputationGate: { max: new Decimal(0) },
      position: { x: 0, y: 2 },
      effects: [
        { type: "activityYieldMultiplier" as const, target: "passwordCracking", value: new Decimal(1.4) },
        { type: "reputationLossMultiplier" as const, value: new Decimal(1.2) },
      ],
    },
    distributedIntrusionTooling: {
      path: "blackhat" as const,
      cost: { crypto: new Decimal(35), compute: new Decimal(25) },
      prerequisites: ["exploitAutomation"] as string[],
      reputationGate: { max: new Decimal(-25) },
      position: { x: 1, y: 2 },
      effects: [
        { type: "activityYieldMultiplier" as const, target: "botnetExpansion", value: new Decimal(1.5) },
        { type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.15) },
      ],
    },
    zeroDaySupplyChain: {
      path: "blackhat" as const,
      cost: { crypto: new Decimal(120), money: new Decimal(120) },
      prerequisites: ["distributedIntrusionTooling"] as string[],
      reputationGate: { alignment: "blackhat" as const },
      position: { x: 2, y: 2 },
      effects: [
        { type: "activityUnlock" as const, target: "zeroDayResearch", value: new Decimal(1) },
        { type: "upgradeUnlock" as const, target: "exploitPrototypeKit", value: new Decimal(1) },
        { type: "activityYieldMultiplier" as const, target: "zeroDayResearch", value: new Decimal(1.5) },
      ],
    },
  },

  prestige: {
    protocolReset: {
      requirement: { crypto: new Decimal(1000) },
      resetsResources: ["money", "crypto", "compute"] as const,
      preservesResearch: false,
      rewardResource: "compute" as const,
      rewardAmount: new Decimal(25),
    },
  },

  scaling: {
    softcapThreshold: new Decimal("1e100"),
    softcapPower: new Decimal(0.5),
  },

  manualActionScaling: {
    reputation: {
      maxBoostMultiplier: new Decimal(1.6),
      maxPenaltyMultiplier: new Decimal(0.55),
      curveReputationForMax: new Decimal(200),
      greyNeutralThreshold: new Decimal(25),
    },
  },

  actions: {
    scanNetwork: {
      type: "instant" as const,
      path: "shared" as const,
      baseCost: {},
      baseReward: { money: new Decimal(2) },
      reputationEffect: new Decimal(0.01),
      reputationScaling: true,
      rewardVariance: new Decimal(0.2),
      cooldownMs: 0,
    },
    mineLocally: {
      type: "duration" as const,
      path: "shared" as const,
      durationMs: 60_000,
      baseCost: {},
      baseReward: { crypto: new Decimal(4) },
      reputationEffect: new Decimal(0),
      reputationScaling: true,
      computeScaling: {
        enabled: true,
        freeComputeSlope: new Decimal(0.04),
        maxMultiplier: new Decimal(4),
      },
      rewardVariance: new Decimal(0),
      cooldownMs: 0,
    },
    bugBounty: {
      type: "instant" as const,
      path: "whitehat" as const,
      baseCost: { money: new Decimal(1) },
      baseReward: { money: new Decimal(12) },
      reputationEffect: new Decimal(0.25),
      reputationScaling: true,
      rewardVariance: new Decimal(0.25),
      cooldownMs: 0,
    },
    passwordAttempt: {
      type: "instant" as const,
      path: "blackhat" as const,
      baseCost: { compute: new Decimal(0.2) },
      baseReward: { money: new Decimal(8), crypto: new Decimal(1.5) },
      reputationEffect: new Decimal(-0.35),
      successChance: new Decimal(0.52),
      rewardVariance: new Decimal(0.4),
      failureRewardMultiplier: new Decimal(0.1),
      reputationScaling: true,
      computeScaling: {
        enabled: true,
        freeComputeSlope: new Decimal(0.015),
        maxMultiplier: new Decimal(2),
      },
      cooldownMs: 0,
    },
  },

  tasks: {
    earnSeedMoney: {
      type: "resourceThreshold" as const,
      requirement: { resource: "money" as const, amount: new Decimal(1e3) },
      reward: { money: new Decimal(50) },
      recommended: true,
      pathHint: "shared" as const,
    },
    mineSeedCrypto: {
      type: "resourceThreshold" as const,
      requirement: { resource: "crypto" as const, amount: new Decimal(1e2) },
      reward: { crypto: new Decimal(10) },
      recommended: true,
      pathHint: "shared" as const,
    },
    whitehatCredibility: {
      type: "reputationThreshold" as const,
      requirement: { amount: new Decimal(50) },
      reward: { reputation: new Decimal(5), money: new Decimal(75) },
      recommended: true,
      pathHint: "whitehat" as const,
    },
    blackhatNotoriety: {
      type: "reputationThreshold" as const,
      requirement: { amount: new Decimal(-50) },
      reward: { reputation: new Decimal(-5), crypto: new Decimal(20) },
      recommended: false,
      pathHint: "blackhat" as const,
    },
    passwordPractice: {
      type: "actionCount" as const,
      requirement: { actionId: "passwordAttempt", count: 10 },
      reward: { money: new Decimal(40), crypto: new Decimal(8) },
      recommended: true,
      pathHint: "blackhat" as const,
    },
    firstActivityLevel: {
      type: "activityLevel" as const,
      requirement: { activityId: "basicCryptoMining", level: 1 },
      reward: { money: new Decimal(30), compute: new Decimal(2) },
      recommended: true,
      pathHint: "shared" as const,
    },
    firstUpgrade: {
      type: "researchCompletion" as const,
      requirement: { researchId: "parallelProcessing" },
      reward: { compute: new Decimal(5) },
      recommended: true,
      pathHint: "shared" as const,
    },
  },

  upgrades: {
    miningFirmwareOptimization: {
      scope: "activity" as const,
      activityId: "basicCryptoMining",
      cost: { compute: new Decimal(5) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 3,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.5) }],
    },
    thermalLoadBalancing: {
      scope: "activity" as const,
      activityId: "basicCryptoMining",
      cost: { money: new Decimal(20) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(2),
      maxLevel: 2,
      effects: [{ type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.25) }],
    },
    leaseContractAutomation: {
      scope: "activity" as const,
      activityId: "computeLeasing",
      cost: { money: new Decimal(15) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 3,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.5) }],
    },
    indexCompression: {
      scope: "activity" as const,
      activityId: "dataIndexing",
      cost: { compute: new Decimal(8) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 2,
      effects: [{ type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.25) }],
    },
    reconAutomation: {
      scope: "activity" as const,
      activityId: "bugBountyHunting",
      cost: { money: new Decimal(25) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 3,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.5) }],
    },
    responsibleDisclosurePipeline: {
      scope: "activity" as const,
      activityId: "bugBountyHunting",
      cost: { money: new Decimal(50) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(2),
      maxLevel: 2,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.75) }],
      reputationGate: { min: new Decimal(10) },
    },
    auditToolchain: {
      scope: "activity" as const,
      activityId: "defensiveAudit",
      cost: { money: new Decimal(30) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 3,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.5) }],
    },
    signatureCorrelation: {
      scope: "activity" as const,
      activityId: "threatIntelAnalysis",
      cost: { money: new Decimal(40) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 2,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.75) }],
      requiresResearchUnlock: true,
    },
    gpuCrackingRig: {
      scope: "activity" as const,
      activityId: "passwordCracking",
      cost: { crypto: new Decimal(5) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 3,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(2) }],
    },
    credentialStuffingScripts: {
      scope: "activity" as const,
      activityId: "passwordCracking",
      cost: { money: new Decimal(10) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 2,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(1.5) }],
    },
    botnetCommandLayer: {
      scope: "activity" as const,
      activityId: "botnetExpansion",
      cost: { crypto: new Decimal(8) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 2,
      effects: [{ type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.3) }],
    },
    exploitPrototypeKit: {
      scope: "activity" as const,
      activityId: "zeroDayResearch",
      cost: { crypto: new Decimal(15) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(1.5),
      maxLevel: 2,
      effects: [{ type: "activityYieldMultiplier" as const, value: new Decimal(2) }],
      requiresResearchUnlock: true,
    },
    encryptedChannels: {
      scope: "global" as const,
      cost: { compute: new Decimal(15) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(2),
      maxLevel: 3,
      effects: [{ type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.1) }],
    },
    networkOptimizer: {
      scope: "global" as const,
      cost: { money: new Decimal(100) },
      costScaling: "exponential" as const,
      costScalingRate: new Decimal(2),
      maxLevel: 2,
      effects: [{ type: "computeEfficiencyMultiplier" as const, value: new Decimal(1.15) }],
    },
  },
} as const;
